version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=grocery_store
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 20
    volumes:
      - ./db:/var/lib/mysql
  backend:
    container_name: backend
    depends_on:
      mysqldb: 
        condition: service_healthy
    build: ./backend
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend
    ports:
      - 80:80